[General]
path=..

[SSP]
imf_type=kroupa
imf_type_options=[kroupa,salpeter,chabrier] 
ssp_mass=6
binary_frac=0.5
min_binary_mass_ratio=0.1
phot_err=0.01
xs=0.0
ys=0.0

[AMR_grid]
model=Padova
model_options=[Padova,MIST,Basti]
age_scale=log
age_min=0.01
age_max=13.7
n_age=136
n_age_options=[68,138,272] 
met_scale=lin
met_min=-2.0
met_max=0.5
n_met=48
n_met_options=[24,48]
met_sun=0.0152
save_isochrone_figs=100
# if save_isochrone_figs(=k)==0, no figures will be saved, if k>0 then each k-th will be saved

[CMD_grid]
gaia_file=../dat/gaia_samples/gaiadr3_Av05.all.2kpc.h5
gaia_file_key=dat
gmag_col=M_G
bp_col=none
rp_col=none
bprp_col=BP_RP
type=voronoi
sn=6.5
scale=3e5
nx=200
#sn=6.5
#scale=3e5

[Fitting]
model_name=run11
eps=10
initial_guess_options=[uniform,blob,gradient,cvxopt,../results/large_model/solution.h5]
initial_guess=cvxopt
method=GD
cmd_to_fit=gaiadr3_Av01.all.1kpc
nsave=1000
max_step=50
fittype_options=[default,rel,abs,new]
fittype=rel
add_time_stamp=no
cmd_density_range=1e-4
save_each_step=no
